name: CD

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DB_NAME: mydatabase
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  AWS_S3_ACCESS_KEY: ${{ secrets.AWS_S3_ACCESS_KEY }}
  AWS_S3_SECRET_KEY: ${{ secrets.AWS_S3_SECRET_KEY }}
  MAIL_USERNAME: ${{ secrets.MAIL_USERNAME}}
  MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Dynamic JWT Secret
        run: |
          # Generate a 64-byte hex string
          DYNAMIC_JWT=$(openssl rand -hex 64)
          # Mask it so it doesn't show up in GitHub logs
          echo "::add-mask::$DYNAMIC_JWT"
          # Save it to the environment for subsequent steps
          echo "JWT_SECRET=$DYNAMIC_JWT" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,prefix={{branch}}-
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max


      - name: Deploy to Docker on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: REGISTRY,IMAGE_NAME,DB_NAME,DB_USER,DB_PASSWORD,GITHUB_ACTOR,GOOGLE_CLIENT_ID,GOOGLE_CLIENT_SECRET,AWS_S3_ACCESS_KEY,AWS_S3_SECRET_KEY,MAIL_USERNAME,MAIL_PASSWORD,JWT_SECRET
          script: |
            # Define the image string inside the script for safety
            IMAGE="${REGISTRY}/${IMAGE_NAME}:latest"
            
            echo "== LOGIN =="
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login $REGISTRY -u $GITHUB_ACTOR --password-stdin
            
            echo "== PULL =="
            docker pull $IMAGE
            
            echo "== STOP =="
            docker stop my-app-container || true
            docker rm my-app-container || true
            
            echo "== RUN =="
            docker run -d \
              --name my-app-container \
              --network app-network \
              --restart always \
              -p 8080:8080 \
              -e SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/$DB_NAME \
              -e DB_USER="$DB_USER" \
              -e DB_PASSWORD="$DB_PASSWORD" \
              -e GOOGLE_CLIENT_ID="$GOOGLE_CLIENT_ID" \
              -e GOOGLE_CLIENT_SECRET="$GOOGLE_CLIENT_SECRET" \
              -e AWS_S3_ACCESS_KEY="$AWS_S3_ACCESS_KEY" \
              -e AWS_S3_SECRET_KEY="$AWS_S3_SECRET_KEY" \
              -e MAIL_USERNAME="$MAIL_USERNAME" \
              -e MAIL_PASSWORD:"$MAIL_PASSWORD" \
              -e JWT_SECRET="$JWT_SECRET" \
              $IMAGE
            
            echo "== PRUNE =="
            docker image prune -f
